services:
  wrapper:
    depends_on:
      frontend:
        condition: service_healthy
    build:
      context: ./wrapper
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 2s
    ports:
      - "8080:80"
  frontend:
    build:
      context: .
    healthcheck:
      test: "curl -f http://localhost:3000 || exit 1"
      interval: 2s
    environment:
      PORT: 3000
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
  tests:
    depends_on:
      wrapper:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./features/Dockerfile
    ipc: host # Keeps chrome from OOMing
    environment:
      BASE_URL: "http://wrapper:80"
    volumes:
      - ./features/tests:/app/tests
    ports:
      - "3001:3001"
