services:
  wrapper:
    build:
      context: ./features/wrapper
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    ports:
      - "8080:80"
    depends_on:
      frontend:
        condition: service_healthy
  frontend:
    healthcheck:
      test: "curl -f http://localhost:3000 || exit 1"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    volumes:
      - ./app/src:/app/src
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
  tests:
    build:
      context: .
      dockerfile: ./features/Dockerfile
    ipc: host # Keeps chrome from OOMing
    volumes:
      - ./features:/app/features
    depends_on:
      wrapper:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      BASE_URL: "http://wrapper:80"
