services:
  wrapper:
    build:
      context: ./wrapper-app
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports:
      - "8080:80"
    depends_on:
      frontend:
        condition: service_healthy
  frontend:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    build:
      context: ./app
    environment:
      PORT: 3000
    volumes:
      - ./app/src:/app/src
    ports:
      - "5173:3000"
    command: ["npm", "run", "_dev"]
  tests:
    build:
      context: ./app
      dockerfile: Dockerfile.tests
    ipc: host # Keeps chrome from OOMing
    volumes:
      - ./app/features:/app/features
    depends_on:
      wrapper:
        condition: service_healthy
    network_mode: host # Allows container access to public frontend
    environment:
      BASE_URL: "http://localhost:8080" # Public frontend port
